variable "region" {}
variable "candidate" {}
variable "vpc_cidr" {}
variable "tf_ingress_snet_az1_cidr" {}
variable "tf_ingress_snet_az2_cidr" {}
variable "tf_private_snet_az1_cidr" {}
variable "tf_private_snet_az2_cidr" {}
variable "project_name" {}
variable "production_cidr_blocks" {}